# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Jonathan/Desktop/fp8/fp4/Our_processor/Processor_top_level.cache/wt [current_project]
set_property parent.project_path C:/Users/Jonathan/Desktop/fp8/fp4/Our_processor/Processor_top_level.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem C:/Users/Jonathan/Desktop/fp8/fp4/memfile.dat
read_vhdl -library xil_defaultlib {
  C:/Users/Jonathan/Desktop/fp8/fp4/Dpu_top.vhd
  C:/Users/Jonathan/Desktop/fp8/fp4/Flip_Flop_register.vhd
  C:/Users/Jonathan/Desktop/fp8/fp4/Processor_top_level.vhd
  C:/Users/Jonathan/Desktop/fp8/fp4/alu.vhd
  C:/Users/Jonathan/Desktop/fp8/fp4/alu_decoder.vhd
  C:/Users/Jonathan/Desktop/fp8/fp4/control_unit.vhd
  C:/Users/Jonathan/Desktop/fp8/fp4/four_bit_adder.vhd
  C:/Users/Jonathan/Desktop/fp8/fp4/gen_six_bit_mux.vhd
  C:/Users/Jonathan/Desktop/fp8/fp4/generic_left_shift.vhd
  C:/Users/Jonathan/Desktop/fp8/fp4/instr_mem.vhd
  C:/Users/Jonathan/Desktop/fp8/fp4/main_decoder.vhd
  C:/Users/Jonathan/Desktop/fp8/fp4/processor_top.vhd
  C:/Users/Jonathan/Desktop/fp8/fp4/register_file.vhd
  C:/Users/Jonathan/Desktop/fp8/fp4/val_extender.vhd
  C:/Users/Jonathan/Desktop/fp8/fp4/processor_sim.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Jonathan/Desktop/fp8/fp4/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Jonathan/Desktop/fp8/fp4/Nexys4DDR_Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top processor_sim -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef processor_sim.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file processor_sim_utilization_synth.rpt -pb processor_sim_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
